### ISSUE TITLE
How to set it up with Grails 3 ?

### ISSUE THREAD

**Issue by salex772** [davidtinker/grails-handlebars#4]
I couldn't compile it and the package is not found in bintray.
Could you provide an instruction how to install that? Thanks.

**Comment by davidtinker** [comment]
This plugin only works with Grails 2.x. Grails 3 requires very different plugins. Its probably easiest to just copy the library dependencies from BuildConfig.groovy into your projects build.gradle + copy and paste the service and tag lib.

**Comment by salex772** [comment]
Ok, please update information here that it is only for 2.x.x I tooks hours from testerday.

**Comment by davidtinker** [comment]
Will do. BuildConfig.groovy is in grails-app/conf. This is the line you need:

    runtime 'com.github.jknack:handlebars:2.2.2'
